# action.yml
name: 'Mvn cmd'
author: https://github.com/qcastel
description: 'Wrap maven command into a docker image'
branding:
  color: blue
  icon: unlock
inputs:

  maven-repo-server-id:
    description: 'Maven server repository id to push the artefacts to'
    required: true
  maven-repo-server-username:
    description: 'Maven server repository username'
    required: true
  maven-repo-server-password:
    description: 'Maven server repository password'
    required: true
  maven-args:
    description: 'The maven arguments'
    required: false
    default: ''

  m2-home-folder:
    description: 'M2 home folder'
    required: false
    default: '/root/.m2'


runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - mvn-action.sh
    - ${{ inputs.maven-args }}
  env:
    MAVEN_REPO_SERVER_ID: ${{ inputs.maven-repo-server-id }}
    MAVEN_REPO_SERVER_USERNAME: ${{ inputs.maven-repo-server-username }}
    MAVEN_REPO_SERVER_PASSWORD: ${{ inputs.maven-repo-server-password }}
    MAVEN_ARGS: ${{ inputs.maven-args }}
    
    M2_HOME_FOLDER: ${{ inputs.m2-home-folder}}

